[package]
name = "httpcam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.12"
tinyjson = "2"
argh = "0.1.12"

[dependencies.nokhwa]
version = "0.10.0"
features = ["input-native"]
